services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres-dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ${PROJECT_ROOT}/out/pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  redis-insight:
    image: redislabs/redisinsight
    container_name: redis-gui
    ports:
      - "5540:5540"
    restart: unless-stopped

volumes:
  httpgohandlers-postgresql_postgres_data:
    external: true
  redis_data: